package com.kontrol.app.ui

import android.content.Context
import androidx.compose.foundation.background
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Brush
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import androidx.navigation.compose.*
import com.kontrol.app.data.*
import kotlinx.coroutines.launch
import java.time.LocalDate
import java.time.LocalTime
import java.time.format.DateTimeFormatter
import java.text.NumberFormat
import java.util.Locale

private val api get()=ApiFactory.api
private val fmt=DateTimeFormatter.ofPattern("HH:mm")

@Composable fun KontrolApp(context:Context){
 val session=remember{SessionManager(context)}; var token by remember{mutableStateOf<String?>(null)}; var loading by remember{mutableStateOf(true)}
 LaunchedEffect(Unit){token=session.token(); ApiFactory.tokenProvider={token}; loading=false}
 if(loading)return
 if(token==null) LoginScreen({email,pwd->val r=api.login(LoginRequest(email,pwd));if(r.isSuccessful){token=r.body()!!.token;session.save(token!!)}},{email,pwd,name->val r=api.register(RegisterRequest(name,email,pwd));if(r.isSuccessful){token=r.body()!!.token;session.save(token!!)}})
 else MainShell(onLogout={session.clear();token=null})
}

@Composable private fun MainShell(onLogout:()->Unit){
 val nav=rememberNavController(); val entries=listOf("home","finance","work","routine","more")
 Scaffold(bottomBar={NavigationBar{entries.forEach{route->val selected=nav.currentBackStackEntryAsState().value?.destination?.route==route;NavigationBarItem(selected, {nav.navigate(route){popUpTo("home");launchSingleTop=true}}, {Icon(when(route){"home"->Icons.Default.Home;"finance"->Icons.Default.AccountBalanceWallet;"work"->Icons.Default.AccessTime;"routine"->Icons.Default.CheckCircle;else->Icons.Default.MoreHoriz},null);Text(when(route){"home"->"Início";"finance"->"Finanças";"work"->"Trabalho";"routine"->"Rotina";else->"Mais"})})}}}){pad->NavHost(nav,"home",Modifier.padding(pad)){composable("home"){HomeScreen()};composable("finance"){FinanceScreen()};composable("work"){WorkScreen()};composable("routine"){RoutineScreen()};composable("more"){MoreScreen(onLogout)}}}
}

@Composable private fun LoginScreen(onLogin:suspend(String,String)->Unit,onRegister:suspend(String,String,String)->Unit){var email by remember{mutableStateOf("")};var pwd by remember{mutableStateOf("")};var name by remember{mutableStateOf("")};var register by remember{mutableStateOf(false)};var msg by remember{mutableStateOf("")};val scope=rememberCoroutineScope();Box(Modifier.fillMaxSize().background(Brush.verticalGradient(listOf(Color(0xFF1565C0),Color(0xFF55B36B)))),Alignment.Center){Card(Modifier.padding(24.dp).fillMaxWidth(),shape=RoundedCornerShape(28.dp)){Column(Modifier.padding(24.dp),verticalArrangement=Arrangement.spacedBy(12.dp)){Text("KONTROL",fontSize=32.sp,fontWeight=FontWeight.Bold,color=Color(0xFF1976D2));Text(if(register)"Crie sua conta":"Organize sua vida em um só lugar",fontSize=16.sp);if(register)OutlinedTextField(name,{name=it},label={Text("Nome")},Modifier.fillMaxWidth());OutlinedTextField(email,{email=it},label={Text("E-mail")},Modifier.fillMaxWidth());OutlinedTextField(pwd,{pwd=it},label={Text("Senha")},Modifier.fillMaxWidth());Button({scope.launch{try{if(register)onRegister(email,pwd,name)else onLogin(email,pwd)}catch(e:Exception){msg="Não foi possível conectar à API."}}},Modifier.fillMaxWidth()){Text(if(register)"Criar conta" else "Entrar")};TextButton({register=!register}){Text(if(register)"Já tenho uma conta" else "Criar uma conta")};if(msg.isNotBlank())Text(msg,color=MaterialTheme.colorScheme.error)}}}}}

@Composable private fun Header(title:String,subtitle:String?=null){Column(Modifier.padding(horizontal=20.dp,vertical=18.dp)){Text(title,fontSize=26.sp,fontWeight=FontWeight.Bold,color=Color(0xFF17324D));subtitle?.let{Text(it,color=Color.Gray)}}}
@Composable private fun HomeScreen(){val scope=rememberCoroutineScope();var d by remember{mutableStateOf<DashboardDto?>(null)};LaunchedEffect(Unit){d=api.dashboard().body()};LazyColumn(Modifier.fillMaxSize()){item{Header("Olá! 👋",LocalDate.now().format(DateTimeFormatter.ofPattern("dd 'de' MMMM")))};item{if(d==null)LinearProgressIndicator(Modifier.fillMaxWidth().padding(horizontal=20.dp)) else Column(Modifier.padding(horizontal=20.dp),verticalArrangement=Arrangement.spacedBy(12.dp)){SummaryCard("💰 Finanças","Saldo atual",money(d!!.finance.balance),Color(0xFF48A868));SummaryCard("⏱️ Trabalho","Horas hoje",minutes(d!!.work.workedMinutes),Color(0xFF258AC2));SummaryCard("✓ Rotina","Tarefas concluídas","${d!!.routine.completedTasks}/${d!!.routine.totalTasks}",Color(0xFF7B61C8));SummaryCard("🛒 Mercado","Itens pendentes",d!!.shopping.pendingItems.toString(),Color(0xFFE68A2E))}}}}
@Composable private fun SummaryCard(icon:String,label:String,value:String,color:Color){Card(shape=RoundedCornerShape(20.dp)){Row(Modifier.fillMaxWidth().background(Brush.horizontalGradient(listOf(color,color.copy(alpha=.7f))).padding(18.dp)),verticalAlignment=Alignment.CenterVertically){Text(icon,fontSize=28.sp);Spacer(Modifier.width(12.dp));Column{Text(label,color=Color.White);Text(value,color=Color.White,fontSize=22.sp,fontWeight=FontWeight.Bold)}}}}

@Composable private fun FinanceScreen(){var list by remember{mutableStateOf<List<TransactionDto>>(emptyList())};var show by remember{mutableStateOf(false)};val scope=rememberCoroutineScope();fun reload(){scope.launch{list=api.transactions().body()?:emptyList()}};LaunchedEffect(Unit){reload()};Column{Header("Finanças","Receitas e despesas em um só lugar");Button({show=true},Modifier.padding(horizontal=20.dp).fillMaxWidth(),shape=RoundedCornerShape(14.dp)){Icon(Icons.Default.Add,null);Spacer(Modifier.width(8.dp));Text("Nova movimentação")};LazyColumn(Modifier.padding(12.dp)){items(list){t->Card(Modifier.fillMaxWidth().padding(5.dp)){ListItem(headlineContent={Text(t.description?:t.type)},supportingContent={Text(t.date)},trailingContent={Text((if(t.type=="EXPENSE")"- " else "+ ")+money(t.amount),fontWeight=FontWeight.Bold)})}}}};if(show)TransactionDialog({show=false;reload()})}
@Composable private fun TransactionDialog(onDone:()->Unit){var type by remember{mutableStateOf("EXPENSE")};var amount by remember{mutableStateOf("")};var desc by remember{mutableStateOf("")};AlertDialog(onDismissRequest=onDone,title={Text("Nova movimentação")},text={Column(verticalArrangement=Arrangement.spacedBy(8.dp)){Row{FilterChip(type=="EXPENSE",{type="EXPENSE"},{Text("Despesa")});Spacer(Modifier.width(8.dp));FilterChip(type=="INCOME",{type="INCOME"},{Text("Receita")})};OutlinedTextField(amount,{amount=it},label={Text("Valor")});OutlinedTextField(desc,{desc=it},label={Text("Descrição")})}},confirmButton={Button({onDone();val v=amount.toDoubleOrNull()?:0.0;CoroutineScope(kotlinx.coroutines.Dispatchers.Main).launch{api.createTransaction(TransactionRequest(type,v,desc,LocalDate.now().toString(),null,null))}}){Text("Salvar")}},dismissButton={TextButton(onDone){Text("Cancelar")}})}

@Composable private fun WorkScreen(){val date=LocalDate.now().toString();var record by remember{mutableStateOf<WorkRecordDto?>(null)};var now by remember{mutableStateOf(LocalTime.now().format(fmt))};val scope=rememberCoroutineScope();LaunchedEffect(Unit){record=api.work(date).body()};LaunchedEffect(Unit){while(true){now=LocalTime.now().format(fmt);kotlinx.coroutines.delay(1000)}};Column(Modifier.fillMaxSize()){Box(Modifier.fillMaxWidth().background(Brush.horizontalGradient(listOf(Color(0xFF1565C0),Color(0xFF55B36B))))){Row(Modifier.padding(20.dp),verticalAlignment=Alignment.CenterVertically){Text("‹",fontSize=38.sp,color=Color.White);Text("Marcação de Ponto",Modifier.weight(1f),fontSize=25.sp,fontWeight=FontWeight.Bold,color=Color.White)}};LazyColumn{item{Row(Modifier.padding(18.dp),horizontalArrangement=Arrangement.spacedBy(8.dp)){TimeCard("⏰","Entrada",record?.entryTime?:"--:--");TimeCard("🍴","Saída",record?.breakStart?:"--:--");TimeCard("💼","Volta",record?.breakEnd?:"--:--");TimeCard("🕘","Saída",record?.exitTime?:"--:--")}};item{Row(Modifier.padding(horizontal=18.dp),horizontalArrangement=Arrangement.spacedBy(12.dp)){StatCard("◷","Horas Feitas",minutes(record?.workedMinutes?:0),Color(0xFF258AC2));StatCard("▤","Total a Receber",money((record?.workedMinutes?:0)/60.0*16.8),Color(0xFF72A85B))}};item{Button({scope.launch{val r=record;val n=now;val req=when{r==null->WorkRecordRequest(date,n,null,null,null);r.breakStart==null->WorkRecordRequest(date,r.entryTime,n,null,null);r.breakEnd==null->WorkRecordRequest(date,r.entryTime,r.breakStart,n,null);r.exitTime==null->WorkRecordRequest(date,r.entryTime,r.breakStart,r.breakEnd,n);else->null};if(req!=null){record=if(r==null)api.createWork(req).body() else api.updateWork(r.id,req).body()}}},Modifier.padding(18.dp).fillMaxWidth(),shape=RoundedCornerShape(14.dp)){Text("Registrar ponto • $now",fontSize=18.sp)}};item{Text("Histórico do mês",Modifier.padding(20.dp),fontWeight=FontWeight.Bold,fontSize=20.sp)};item{Card(Modifier.padding(horizontal=18.dp)){Column{repeat(8){day->ListItem(headlineContent={Text("${day+1}")},supportingContent={Text("8h")},trailingContent={Text(money(134.40))})};Divider();ListItem(headlineContent={Text("Total de Horas")},trailingContent={Text("72h  •  ${money(1209.60)}",fontWeight=FontWeight.Bold))}}}}}}
@Composable private fun TimeCard(icon:String,title:String,time:String){Card(Modifier.weight(1f),shape=RoundedCornerShape(16.dp)){Column(Modifier.padding(8.dp),horizontalAlignment=Alignment.CenterHorizontally){Text(icon,fontSize=24.sp);Text(title,fontWeight=FontWeight.SemiBold);Text(time,fontSize=17.sp)}}}
@Composable private fun StatCard(icon:String,title:String,value:String,color:Color){Card(Modifier.weight(1f)){Row(Modifier.fillMaxWidth().background(Brush.horizontalGradient(listOf(color,color.copy(alpha=.7f))).padding(15.dp)),verticalAlignment=Alignment.CenterVertically){Text(icon,fontSize=25.sp,color=Color.White);Spacer(Modifier.width(8.dp));Column{Text(title,color=Color.White);Text(value,fontSize=21.sp,fontWeight=FontWeight.Bold,color=Color.White)}}}}

@Composable private fun RoutineScreen(){var tasks by remember{mutableStateOf<List<TaskDto>>(emptyList())};var title by remember{mutableStateOf("")};val scope=rememberCoroutineScope();fun reload(){scope.launch{tasks=api.tasks().body()?:emptyList()}};LaunchedEffect(Unit){reload()};Column{Header("Minha rotina","Organize o que precisa ser feito hoje");Row(Modifier.padding(horizontal=20.dp),verticalAlignment=Alignment.CenterVertically){OutlinedTextField(title,{title=it},label={Text("Nova tarefa")},Modifier.weight(1f));IconButton({if(title.isNotBlank())scope.launch{api.createTask(TaskRequest(title,null,LocalDate.now().toString()));title="";reload()}}){Icon(Icons.Default.Add,null)}};LazyColumn{items(tasks){t->ListItem(headlineContent={Text(t.title,fontWeight=FontWeight.SemiBold)},supportingContent={Text(t.description?:"Hoje")},leadingContent={Checkbox(t.completed,{scope.launch{api.updateTask(t.id,TaskRequest(t.title,t.description,t.date,t.priority,!t.completed));reload()}})})}}}}

@Composable private fun MoreScreen(onLogout:()->Unit){var notes by remember{mutableStateOf<List<NoteDto>>(emptyList())};var shopping by remember{mutableStateOf<List<ShoppingListDto>>(emptyList())};var showNote by remember{mutableStateOf(false)};var showList by remember{mutableStateOf(false)};val scope=rememberCoroutineScope();LaunchedEffect(Unit){notes=api.notes().body()?:emptyList();shopping=api.shopping().body()?:emptyList()};Column{Header("Mais","Outras ferramentas do Kontrol");Card(Modifier.padding(20.dp).fillMaxWidth().clickable{showNote=true}){ListItem(headlineContent={Text("📝 Notas")},supportingContent={Text("${notes.size} notas")})};Card(Modifier.padding(horizontal=20.dp).fillMaxWidth().clickable{showList=true}){ListItem(headlineContent={Text("🛒 Mercado")},supportingContent={Text("${shopping.size} listas")})};Spacer(Modifier.height(20.dp));TextButton(onLogout,Modifier.padding(20.dp)){Text("Sair da conta")}};if(showNote)NoteDialog({showNote=false;scope.launch{notes=api.notes().body()?:emptyList()}});if(showList)ShoppingDialog({showList=false;scope.launch{shopping=api.shopping().body()?:emptyList()}})}
@Composable private fun NoteDialog(onDone:()->Unit){var title by remember{mutableStateOf("")};var content by remember{mutableStateOf("")};AlertDialog(onDismissRequest=onDone,title={Text("Nova nota")},text={Column{OutlinedTextField(title,{title=it},label={Text("Título")});OutlinedTextField(content,{content=it},label={Text("Conteúdo")})}},confirmButton={Button({CoroutineScope(kotlinx.coroutines.Dispatchers.Main).launch{api.createNote(NoteRequest(title,content));onDone()}}){Text("Salvar")}},dismissButton={TextButton(onDone){Text("Cancelar")}})}
@Composable private fun ShoppingDialog(onDone:()->Unit){var name by remember{mutableStateOf("")};AlertDialog(onDismissRequest=onDone,title={Text("Nova lista")},text={OutlinedTextField(name,{name=it},label={Text("Nome da lista")})},confirmButton={Button({CoroutineScope(kotlinx.coroutines.Dispatchers.Main).launch{api.createShopping(ShoppingListRequest(name));onDone()}}){Text("Criar")}},dismissButton={TextButton(onDone){Text("Cancelar")}})}

private fun money(v:Double)=NumberFormat.getCurrencyInstance(Locale("pt","BR")).format(v)
private fun minutes(m:Int):String="${m/60}h ${m%60}min"
